# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Release"
	lane :release do
		build

		upload_to_app_store(
			force: true,
			automatic_release: true,
			submit_for_review: true,
			reject_if_possible: true,
			submission_information: {
				add_id_info_uses_idfa: false
			}
		)
	end

	desc "Upload metadata"
	lane :upload_metadata do
		upload_to_app_store(
			force: true,
			skip_screenshots: true,
			skip_binary_upload: true,
			automatic_release: true
		)
	end

	# Private

	private_lane :build do
		build_app(
			scheme: "Good Mood"
		)
	end
end
